### signup user
POST http://localhost:3000/auth/signup
Content-Type:  application/json

{
  "firstName":"husban",
  "lastName":"raina",
  "gender":"male",
  "phoneNumber":8082780721,
  "email": "husbanraina1@example.com",
  "password":"123456"
}


###login user
POST  http://localhost:3000/auth/login 
Content-Type: application/json

{
  "email": "husbanraina1@example.com",
  "password": "123456"
}

###sign out user
POST http://localhost:3000/auth/signout

### add task 
POST http://localhost:3000/task/addtask/65fd35daaf93b7a348a74f52
Content-Type : application/json

{
   "taskName": "add task 2.",
   "startTime":"3",
   "endTime":"4"
}

### get all tasks for a specific user
GET http://localhost:3000/task/gettasks/65fd35daaf93b7a348a74f52


### Delete a task 
DELETE http://localhost:3000/task/deletetask/65fd3603af93b7a348a74f59

###update a task
PATCH http://localhost:3000/task/updatetask/65fd360aaf93b7a348a74f5d
Content-Type: application/json

{
  "taskName": "task edited",
  "startTime":"4",
  "endTime":"8"
}






# ###add task
# POST http://localhost:3000/task/addtask
# Content-Type: application/json

# {
#   "content":"exercise"
# }

# ###get all tasks of a specific user
# GET http://localhost:3000/task/gettasks